# Generated by Django 5.1.7 on 2025-04-01 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=42, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('network', models.CharField(default='sepolia', max_length=50)),
                ('deployed', models.BooleanField(default=False)),
                ('deployment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_registries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Data Registry',
                'verbose_name_plural': 'User Data Registries',
            },
        ),
        migrations.CreateModel(
            name='RegistryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('is_authorized', models.BooleanField(default=True)),
                ('image_reference', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_memberships', to=settings.AUTH_USER_MODEL)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='contract.userdataregistry')),
            ],
            options={
                'unique_together': {('registry', 'wallet_address')},
            },
        ),
    ]
