# Generated by Django 5.1.7 on 2025-04-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataregistry',
            name='network',
            field=models.CharField(choices=[('sepolia', 'Ethereum Sepolia Testnet'), ('goerli', 'Ethereum Goerli Testnet'), ('mumbai', 'Polygon Mumbai Testnet')], default='sepolia', max_length=50),
        ),
    ]
